# WARNING - Generated by {fusen} from /dev/flat_business_logic.Rmd: do not edit by hand

test_that("filter_breakfast_data works", {
  output <- filter_breakfast_data(
    breakfast_df = head(breakfast),
    days_chr = c("Friday", "Wednesday"),
    region_chr = "Center"
  )
  expect_equal(
    object = output,
    # The trick is to use dput() here
    expected = structure(
      list(
        day_end = "Weekday",
        start_time = structure(27000, 
                               class = c("hms", "difftime"), units = "secs"),
        day_of_the_week = "Friday",
        domicile = "At home",
        region = "Center"
      ),
      row.names = c(NA, -1L),
      class = "data.frame"
    )
  )
})
