# WARNING - Generated by {fusen} from /dev/flat_business_logic.Rmd: do not edit by hand

#' Filter the breakfast dataset
#' 
#' Filter the breakfast dataset by days in region.
#' 
#' @param breakfast_df A data.frame. The breakfast dataset with at least 
#' the columns `day_of_the_week` and `region`.
#' @param days_chr A character vector. The days of week.
#' @param region_chr A character vector. The regions to select.
#'
#' @return A data.frame.
#' 
#' @importFrom dplyr filter
#' @export
#'
#' @examples
#' filter_breakfast_data(
#'   breakfast_df = breakfast,
#'   days_chr = c("Monday", "Tuesday"),
#'   region_chr = "Center"
#' )
filter_breakfast_data <- function(breakfast_df, days_chr, region_chr) {
  breakfast_df |> 
    filter(
      day_of_the_week %in% days_chr,
      region %in% region_chr
    )
}
